export interface CellTypeRules {
  surviveRange: [number, number];
  birthCondition: (neighbors: number[], selfType: number) => boolean;
  deathCondition?: (neighbors: number[], selfType: number) => boolean;
  /** Type ID that preys on this type (conversion mechanic) */
  predator?: number;
  /** How many predator neighbors needed to convert (default 2) */
  predatorThreshold?: number;
  /** Type ID that counts as "friendly" for survival range */
  symbiont?: number;
  /** Tiebreaker for birth conflicts (1-3, lower = loses ties) */
  conflictPriority: number;
}

export interface CellType {
  id: number;
  name: string;
  emoji: string;
  color: string;
  toxicityWeight: number;
  description: string;
  rules: CellTypeRules;
}

function countType(neighbors: number[], type: number): number {
  return neighbors.filter(n => n === type).length;
}

function countNonEmpty(neighbors: number[]): number {
  return neighbors.filter(n => n !== 0).length;
}

function countDistinctTypes(neighbors: number[]): number {
  return new Set(neighbors.filter(n => n !== 0)).size;
}

/** Count "friendly" neighbors: same type + symbiont type */
function countFriendly(neighbors: number[], selfType: number, symbiont?: number): number {
  return neighbors.filter(n => n === selfType || (symbiont !== undefined && n === symbiont)).length;
}

export const CELL_TYPES: CellType[] = [
  {
    id: 0,
    name: 'Empty',
    emoji: '',
    color: '#c0c0c0',
    toxicityWeight: 0,
    description: 'Nothing here... yet',
    rules: {
      surviveRange: [0, 0],
      birthCondition: () => false,
      conflictPriority: 0,
    },
  },

  // === CYCLE A: SEO Spam (5) -> AI Art (1) -> AI Influencer (6) -> Clickbait (7) -> SEO Spam (5) ===

  {
    id: 1,
    name: 'AI Art',
    emoji: '\u{1F3A8}',
    color: '#FF6B9D',
    toxicityWeight: 0.8,
    description: 'Midjourney-style generated images flooding every feed',
    rules: {
      surviveRange: [1, 3], // Survives in sparse areas too (friendly = self + Influencer)
      symbiont: 6, // AI Influencer counts as friendly for survival
      birthCondition: (neighbors) => countType(neighbors, 1) >= 2 && countType(neighbors, 1) <= 3,
      predator: 5, // SEO Spam farms AI Art
      predatorThreshold: 3, // Harder to farm
      conflictPriority: 2,
    },
  },
  {
    id: 2,
    name: 'ChatGPT Essay',
    emoji: '\u{1F4DD}',
    color: '#74B9FF',
    toxicityWeight: 1.2,
    description: '"As an AI language model..." — you know the rest',
    rules: {
      surviveRange: [1, 4], // Very resilient
      symbiont: 8, // AI Code counts as friendly
      birthCondition: (neighbors) => countType(neighbors, 2) >= 2 && countNonEmpty(neighbors) <= 5,
      predator: 3, // Deepfake debunks essays
      predatorThreshold: 3, // Hard to debunk (persistent)
      conflictPriority: 2,
    },
  },
  {
    id: 3,
    name: 'Deepfake',
    emoji: '\u{1F3AD}',
    color: '#A29BFE',
    toxicityWeight: 2,
    description: 'Face-swapped video content — is anything real anymore?',
    rules: {
      surviveRange: [1, 4], // Resilient (hard to detect)
      birthCondition: (neighbors) => countType(neighbors, 3) >= 2 && countType(neighbors, 3) <= 3,
      deathCondition: (neighbors) => countType(neighbors, 3) >= 6, // Too many fakes become obvious
      predator: 4, // AI Music exposes synthetic audio in deepfakes
      predatorThreshold: 2,
      conflictPriority: 2,
    },
  },
  {
    id: 4,
    name: 'AI Music',
    emoji: '\u{1F3B5}',
    color: '#FDCB6E',
    toxicityWeight: 0.3,
    description: 'Lo-fi beats generated by neural nets to study/relax to',
    rules: {
      surviveRange: [1, 5], // Extremely resilient (music is everywhere)
      birthCondition: (neighbors) => countType(neighbors, 4) >= 2 && countDistinctTypes(neighbors) >= 2,
      predator: 8, // AI Code replaces hand-crafted music
      predatorThreshold: 2,
      conflictPriority: 1, // Lowest — music is non-aggressive
    },
  },
  {
    id: 5,
    name: 'SEO Spam',
    emoji: '\u{1F517}',
    color: '#00B894',
    toxicityWeight: 2.5,
    description: '"Top 10 Best..." listicle farms gaming every search result',
    rules: {
      surviveRange: [1, 4], // Resilient optimizer
      birthCondition: (neighbors) => {
        const same = countType(neighbors, 5);
        const total = countNonEmpty(neighbors);
        return same >= 2 && total >= 2 && total <= 5;
      },
      deathCondition: (neighbors) => {
        // Dies if 3+ of any single other type ("algorithm update")
        const counts = new Map<number, number>();
        for (const n of neighbors) {
          if (n !== 0 && n !== 5) {
            counts.set(n, (counts.get(n) || 0) + 1);
          }
        }
        for (const count of counts.values()) {
          if (count >= 4) return true;
        }
        return false;
      },
      predator: 7, // Clickbait outcompetes SEO
      predatorThreshold: 2,
      conflictPriority: 2,
    },
  },
  {
    id: 6,
    name: 'AI Influencer',
    emoji: '\u{1F916}',
    color: '#E17055',
    toxicityWeight: 1.5,
    description: 'Virtual Instagram models with millions of bot followers',
    rules: {
      surviveRange: [2, 4],
      symbiont: 1, // AI Art counts as friendly
      birthCondition: (neighbors) => {
        return countDistinctTypes(neighbors) >= 3 && countNonEmpty(neighbors) >= 3;
      },
      deathCondition: (neighbors) => {
        const total = countNonEmpty(neighbors);
        const types = countDistinctTypes(neighbors);
        return total === 0 || types <= 1; // Dies without diverse audience
      },
      predator: 1, // AI Art drowns out influencer
      predatorThreshold: 3, // High threshold (symbiosis protects)
      conflictPriority: 1,
    },
  },
  {
    id: 7,
    name: 'Clickbait',
    emoji: '\u{1FAA4}',
    color: '#D63031',
    toxicityWeight: 2,
    description: '"You Won\'t BELIEVE..." thumbnails with red circles',
    rules: {
      surviveRange: [1, 3], // Short-lived but not instant death
      birthCondition: (neighbors) => {
        return countDistinctTypes(neighbors) >= 2 && countNonEmpty(neighbors) >= 3;
      },
      predator: 6, // Influencers co-opt clickbait
      predatorThreshold: 2,
      conflictPriority: 3, // Highest — clickbait grabs attention
    },
  },
  {
    id: 8,
    name: 'AI Code',
    emoji: '\u{1F4BB}',
    color: '#6C5CE7',
    toxicityWeight: 0.5,
    description: 'Stack Overflow copypasta that somehow compiles',
    rules: {
      surviveRange: [2, 4], // Widened for resilience
      birthCondition: (neighbors) => countType(neighbors, 8) >= 2 && countType(neighbors, 8) <= 3,
      predator: 2, // Essays absorb/explain code
      predatorThreshold: 3, // Harder to absorb
      conflictPriority: 2,
    },
  },
];

// Lookup map for O(1) access by ID
export const CELL_TYPE_MAP = new Map<number, CellType>(
  CELL_TYPES.map(t => [t.id, t])
);

export function getCellType(id: number): CellType {
  return CELL_TYPE_MAP.get(id) || CELL_TYPES[0];
}

// Re-export helpers for use in rules-engine
export { countType, countNonEmpty, countDistinctTypes, countFriendly };
