import { useState, useEffect, useRef } from 'react';
import { useSimulationStore } from '../stores/simulation-store';
import { CELL_TYPES } from '../simulation/cell-types';

const GENERIC_HEADLINES = [
  "BREAKING: Local man can't tell if article was written by human or ChatGPT. 'Neither can I,' says the article",
  "Study finds 99% of internet content will be AI-generated by 2027. Study was AI-generated",
  "AI influencer gains 2M followers. Followers also AI-generated",
  "Spotify removes 10,000 AI-generated songs. 10,000 more appear instantly",
  "Man argues with ChatGPT for 3 hours. ChatGPT wins by apologizing",
  "SEO experts warn: 'Google is now just AI talking to AI about AI'",
  "Deepfake of CEO gives better quarterly earnings call than real CEO",
  "Stack Overflow traffic drops 90% as developers just ask ChatGPT instead",
  "AI art wins photography contest. Judges were also AI",
  "LinkedIn flooded with AI-generated thought leadership. No one notices",
  "'I asked AI to write my wedding vows,' says AI-generated bride",
  "AI-generated podcast interviews AI-generated guest about AI-generated news",
  "Local newspaper replaces all journalists with GPT. Readers say quality unchanged",
  "Scientists use AI to discover that AI is making too much content",
  "Clickbait article promises 'You Won't Believe' — reader believes it anyway",
  "AI music label signs AI artist. Contract negotiated by AI lawyer",
  "Tech CEO claims new AI 'definitely not just a wrapper around GPT'",
  "Dead Internet Theory confirmed. Nobody notices because bots are arguing about it",
  "AI generates 50,000 blog posts about why AI-generated content is bad",
  "Man creates deepfake of himself to attend Zoom meetings. Gets promoted",
  "SEO spam article ranks #1 for 'what is real anymore'",
  "AI influencer breaks up with AI boyfriend. Both go viral",
  "New AI model trained exclusively on AI-generated data. Researchers call it 'the ouroboros'",
  "Internet runs out of original content. Starts recycling slop from 2024",
];

function getStateHeadline(): string | null {
  const { populations, toxicity, generation } = useSimulationStore.getState();
  const total = Object.values(populations).reduce((a, b) => a + b, 0);
  if (total === 0) return null;

  const dominant = Object.entries(populations).sort(([, a], [, b]) => b - a)[0];
  const dominantType = CELL_TYPES.find(t => t.id === Number(dominant[0]));
  const dominantPct = Math.round((Number(dominant[1]) / total) * 100);

  if (toxicity.value >= 90) return "ALERT: Internet Toxicity Index exceeds 90%. Experts recommend touching grass";
  if (toxicity.value >= 75) return `WARNING: ${dominantType?.name || 'Unknown slop'} now controls ${dominantPct}% of all content`;
  if (toxicity.value < 10) return "MIRACLE: Internet toxicity at historic low. Scientists baffled";

  if (dominantPct > 50) {
    return `${dominantType?.name || 'AI content'} dominates with ${dominantPct}% market share. Antitrust regulators napping`;
  }

  if (generation > 500) return `Generation ${generation}: The simulation has been running longer than most AI startups`;
  if (generation > 200) return "Observers note the internet ecosystem has achieved 'peak slop'";

  return null;
}

function pickHeadline(): string {
  const stateHeadline = getStateHeadline();
  if (stateHeadline && Math.random() < 0.4) {
    return stateHeadline;
  }
  return GENERIC_HEADLINES[Math.floor(Math.random() * GENERIC_HEADLINES.length)];
}

export function NewsTicker() {
  const [headline, setHeadline] = useState(() => pickHeadline());
  const containerRef = useRef<HTMLDivElement>(null);
  const posRef = useRef(0);
  const spanRef = useRef<HTMLSpanElement>(null);

  // Pick a new headline every 15 seconds — no reactive deps on simulation state
  useEffect(() => {
    const interval = setInterval(() => {
      setHeadline(pickHeadline());
    }, 15000);
    return () => clearInterval(interval);
  }, []);

  // Reset scroll position when headline changes
  useEffect(() => {
    const el = containerRef.current;
    if (el) posRef.current = el.offsetWidth;
  }, [headline]);

  // Scroll animation via rAF — uses refs, no React re-renders
  useEffect(() => {
    const el = containerRef.current;
    const span = spanRef.current;
    if (!el || !span) return;

    posRef.current = el.offsetWidth;
    let raf: number;

    const scroll = () => {
      posRef.current -= 1.5;
      span.style.transform = `translateX(${posRef.current}px)`;

      // Reset when fully scrolled off left
      const spanWidth = span.offsetWidth;
      if (posRef.current < -spanWidth) {
        posRef.current = el.offsetWidth;
      }

      raf = requestAnimationFrame(scroll);
    };

    raf = requestAnimationFrame(scroll);
    return () => cancelAnimationFrame(raf);
  }, [headline]);

  return (
    <div
      ref={containerRef}
      style={{
        overflow: 'hidden',
        whiteSpace: 'nowrap',
        flex: 1,
        position: 'relative',
        height: '100%',
        display: 'flex',
        alignItems: 'center',
      }}
    >
      <span
        ref={spanRef}
        style={{
          position: 'absolute',
          left: 0,
          fontSize: '12px',
          color: '#000',
          fontWeight: 'bold',
          willChange: 'transform',
        }}
      >
        {'\u{1F4F0}'} SLOP NEWS: {headline}
      </span>
    </div>
  );
}
